[31mERROR[39m [2022-04-11 01:10:17.603] (FacturadorElectronicoDev): [36mbin/db.js: Error sincronizando la db:[39m
[31mERROR[39m [2022-04-11 01:10:49.280] (FacturadorElectronicoDev): [36mbin/db.js: Error sincronizando la db:[39m
[31mERROR[39m [2022-04-11 01:11:21.295] (FacturadorElectronicoDev): [36mbin/db.js: Error sincronizando la db:[39m
[31mERROR[39m [2022-04-11 01:11:50.594] (FacturadorElectronicoDev): [36msrc/helpers/db/db.js: Error sincronizando la db:[39m
[31mERROR[39m [2022-04-11 01:14:46.011] (FacturadorElectronicoDev): [36msrc/helpers/db/db.js: Too many keys specified; max 64 keys allowed[39m
    err: {
      "type": "DatabaseError",
      "message": "Too many keys specified; max 64 keys allowed",
      "stack":
          Error: 
              at Query.run (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\sequelize\src\dialects\mysql\query.js:46:25)
              at D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\sequelize\src\sequelize.js:643:28
              at processTicksAndRejections (node:internal/process/task_queues:96:5)
              at Function.sync (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\sequelize\src\model.js:1396:11)
              at Sequelize.sync (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\sequelize\src\sequelize.js:817:35)
      "name": "SequelizeDatabaseError",
      "parent": {
        "type": "Error",
        "message": "Too many keys specified; max 64 keys allowed",
        "stack":
            Error: Too many keys specified; max 64 keys allowed
                at Packet.asError (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\packets\packet.js:712:17)
                at Query.execute (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\commands\command.js:28:26)
                at Connection.handlePacket (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\connection.js:425:32)
                at PacketParser.onPacket (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\connection.js:75:12)
                at PacketParser.executeStart (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
                at Socket.<anonymous> (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\connection.js:82:25)
                at Socket.emit (node:events:526:28)
                at Socket.emit (node:domain:475:12)
                at addChunk (node:internal/streams/readable:315:12)
                at readableAddChunk (node:internal/streams/readable:289:9)
        "code": "ER_TOO_MANY_KEYS",
        "errno": 1069,
        "sqlState": "42000",
        "sqlMessage": "Too many keys specified; max 64 keys allowed",
        "sql": "ALTER TABLE `Users` CHANGE `email` `email` VARCHAR(120) NOT NULL UNIQUE;"
      },
      "original": {
        "type": "Error",
        "message": "Too many keys specified; max 64 keys allowed",
        "stack":
            Error: Too many keys specified; max 64 keys allowed
                at Packet.asError (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\packets\packet.js:712:17)
                at Query.execute (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\commands\command.js:28:26)
                at Connection.handlePacket (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\connection.js:425:32)
                at PacketParser.onPacket (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\connection.js:75:12)
                at PacketParser.executeStart (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\packet_parser.js:75:16)
                at Socket.<anonymous> (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\mysql2\lib\connection.js:82:25)
                at Socket.emit (node:events:526:28)
                at Socket.emit (node:domain:475:12)
                at addChunk (node:internal/streams/readable:315:12)
                at readableAddChunk (node:internal/streams/readable:289:9)
        "code": "ER_TOO_MANY_KEYS",
        "errno": 1069,
        "sqlState": "42000",
        "sqlMessage": "Too many keys specified; max 64 keys allowed",
        "sql": "ALTER TABLE `Users` CHANGE `email` `email` VARCHAR(120) NOT NULL UNIQUE;"
      },
      "sql": "ALTER TABLE `Users` CHANGE `email` `email` VARCHAR(120) NOT NULL UNIQUE;",
      "parameters": {}
    }
[31mERROR[39m [2022-04-11 01:20:18.237] (FacturadorElectronicoDev): [36msrc/helpers/db/db.js: logger is not defined[39m
    err: {
      "type": "ReferenceError",
      "message": "logger is not defined",
      "stack":
          ReferenceError: logger is not defined
              at _callee2$ (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\src\helpers\db\/syncDefaults.js:25:3)
              at tryCatch (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\regenerator-runtime\runtime.js:63:40)
              at Generator.invoke [as _invoke] (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\regenerator-runtime\runtime.js:293:22)
              at Generator.next (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\regenerator-runtime\runtime.js:118:21)
              at asyncGeneratorStep (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
              at _next (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
              at D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
              at new Promise (<anonymous>)
              at Object.<anonymous> (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
              at Object.users (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\src\helpers\db\/syncDefaults.js:23:12)
    }
[31mERROR[39m [2022-04-11 01:29:59.610] (FacturadorElectronicoDev): [36msrc/helpers/db/db.js: LOG_PREFIX is not defined[39m
    err: {
      "type": "ReferenceError",
      "message": "LOG_PREFIX is not defined",
      "stack":
          ReferenceError: LOG_PREFIX is not defined
              at _callee$ (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\src\services\/user.js:12:18)
              at tryCatch (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\regenerator-runtime\runtime.js:63:40)
              at Generator.invoke [as _invoke] (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\regenerator-runtime\runtime.js:293:22)
              at Generator.next (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\regenerator-runtime\runtime.js:118:21)
              at asyncGeneratorStep (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
              at _next (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
              at D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
              at new Promise (<anonymous>)
              at Object.<anonymous> (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
              at Object.hashPassword (D:\Users\USUARIO\Documents\juan-rg\facturador-electronico\backend\src\services\/user.js:10:19)
    }
